ros_topic_map:
  /greenhouse/sensor/environment: "std_msgs/Float32MultiArray"
  /greenhouse/actuator/fan: "std_msgs/Bool"
  /greenhouse/actuator/valve: "std_msgs/Bool"
plugin_config:
  sample_frequency: 1.0
  fan_threshold: 28.0
  valve_threshold: 40.0